**What is NumPy?**

NumPy is a Python library used for working with arrays.

**Why use NumPy?**

In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.

**Numpy arrays are faster than Python lists because they:**

*   Store data contiguously in memory with a uniform data type, allowing for efficient access and processling.
*   Are implemented in highly optimized C and Fortran, enabling vectorized operations that avoid Python's slower interpreted loops.
*   Have less memory overhead per element due to their fixed data type and contiguous storage.



In [ ]:
# Import Numpy
import numpy as np

NumPy is usually imported under the **np** alias

In [ ]:
arr = np.array([1,2,10,15,50])
print(arr)

[ 1  2 10 15 50]


To create an **ndarray**, we can pass a list, tuple or any array-like objet into the **array()** method, and it will be converted into ndarray.

In [ ]:
mat = np.array([[1,2,10,15,50],[3,4,11,16,51]])
print(mat)

[[ 1  2 10 15 50]
 [ 3  4 11 16 51]]


In [10]:
print(mat.ndim)

2


In [13]:
# 2D Arrays
a = np.array([10,50,70,100])

print(a[-2])

70


In [ ]:
# Check Number of Dimensions


Array indexing is the same as accessing an array element

In [ ]:
# Negative Indexing

